DROP TABLE IF EXISTS Diary;

CREATE TABLE Diary (
    DiaryID INT GENERATED ALWAYS AS IDENTITY,
    Text VARCHAR(500) NOT NULL,
    Date DATE DEFAULT CURRENT_DATE,
    Time TIME DEFAULT CURRENT_TIME,
    category VARCHAR(100) NOT NULL,
    PRIMARY KEY (DiaryID)
);


