DROP TABLE IF EXISTS Diary;

CREATE TABLE Diary (
    DiaryID INT GENERATED ALWAYS AS IDENTITY,
    Text VARCHAR(500) NOT NULL,
    Date DATE NOT NULL,
    Time TIME NOT NULL,
    category VARCHAR(100) NOT NULL,
    PRIMARY KEY (DiaryID)
);


