DROP TABLE IF EXISTS Diary;

CREATE TABLE Diary (
    DiaryID INT GENERATED ALWAYS AS IDENTITY,
    Text VARCHAR(500) NOT NULL,
    Date DATE NOT NULL DEFAULT CURRENT_DATE,
    Time TIME NOT NULL DEFAULT CURRENT_TIME,
    category VARCHAR(100) NOT NULL,
    PRIMARY KEY (DiaryID)
);


